version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "13000:5432"
  parser:
    container_name: dev-parser
    image: spaikbrawlstars/parser
    environment:
      pg_host: "postgres"
      pg_port: 5432
      pg_user: "user"
      pg_db_name: "db"
      pg_password: "password"
#    env_file:
#      - ../../parser/.env
    ports:
      - "80:80"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 80"
