"""initial

Revision ID: ad669366a757
Revises: 
Create Date: 2024-02-25 02:40:03.523404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.json_field import Json

# revision identifiers, used by Alembic.
revision: str = 'ad669366a757'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bs4_parsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('search_by_attrs', Json(), nullable=True),
    sa.Column('output_attrs', Json(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('headers', Json(), nullable=True),
    sa.Column('params', Json(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regexp_parsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regexp', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('GROUP', 'FIND_ALL', name='type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_delay', sa.Time(), nullable=False),
    sa.Column('last_check_time', sa.DateTime(), nullable=True),
    sa.Column('send_result_url', sa.String(), nullable=False),
    sa.Column('endpoint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', Json(), nullable=True),
    sa.Column('rule', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['rule'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parser_type', sa.Enum('REGEXP', 'BS4', name='type'), nullable=True),
    sa.Column('parser_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsers')
    op.drop_table('checks')
    op.drop_table('rules')
    op.drop_table('regexp_parsers')
    op.drop_table('endpoints')
    op.drop_table('bs4_parsers')
    # ### end Alembic commands ###
