"""add new parser

Revision ID: bc0f491c7844
Revises: acac822c3d33
Create Date: 2024-03-11 00:11:26.683825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0f491c7844'
down_revision: Union[str, None] = 'acac822c3d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('not_empty_parser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_input', sa.Boolean(), nullable=True),
    sa.Column('linerize_result', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bs4_parsers', sa.Column('only_values', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bs4_parsers', 'only_values')
    op.drop_table('not_empty_parser')
    # ### end Alembic commands ###
